version: '3.7'

services:
    app:
        build:
            context: .
        ports:
            - "5000:5000"
        volumes:
            - './volume:/volume'
#    training:
#        build:
#            context: ./training
#        ports:
#            - "8000:8000"
#        volumes:
#            - './volume:/volume'
#            - '/:/'
